export function getElementText(nativeElement: HTMLElement, dataQa: string): string {
    const foundElement = getElement(nativeElement, dataQa);
    return cleanString(foundElement.textContent);
}

export function getElement(nativeElement: HTMLElement, dataQa: string): HTMLElement {
  const foundElement = nativeElement.querySelector(`[data-qa="${dataQa}"]`) as HTMLElement;
  return existingElement(foundElement, dataQa) as HTMLElement;
}

//This checks that the element exist before returning it, this way 
export function existingElement(foundElement: HTMLElement, dataQa: string) {
  if(!foundElement) {
    throw new Error(`The element for the data-qa="${dataQa}" was not found`);
  } 
  return foundElement;
}

// this clears tabs, new lines and carriage return, 
// I use this is in case there is space in the text that is generated by
// the electron app.
export function cleanString(stringToClean: string): string {
  return stringToClean.trim().replace(/(\r\n\t|\n|\r\t)/gm, '');
}